# Generated by Django 5.2.4 on 2025-10-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
